[window]
opacity = 1.0
[window.padding]
x = 5
y = 5

[scrolling]
history = 10000
multiplier = 3

[terminal.shell]
program = "/opt/local/bin/fish"
args = ["-l"]  # Force login shell

[font]
size = 11.0

[font.normal]
family = "NotoSansM Nerd Font Mono"
style = "Regular"

[font.bold]
family = "NotoSansM Nerd Font Mono"
style = "Bold"

[font.italic]
family = "NotoSansM Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "NotoSansM Nerd Font Mono"
style = "Bold Italic"

[colors.primary]
background = "0x2D2A2E"
foreground = "0xfff1f3"

[colors.normal]
black = "0x2c2525"
red = "0xfd6883"
green = "0xadda78"
yellow = "0xf9cc6c"
blue = "0xf38d70"
magenta = "0xa8a9eb"
cyan = "0x85dacc"
white = "0xfff1f3"

[colors.bright]
black = "0x72696a"
red = "0xfd6883"
green = "0xadda78"
yellow = "0xf9cc6c"
blue = "0xf38d70"
magenta = "0xa8a9eb"
cyan = "0x85dacc"
white = "0xfff1f3"

[cursor.style]
shape = "Beam"


